[tool.pytest.ini_options]
testpaths = "src"
python_files = "*.py"

[tool.pyright]
reportOptionalMemberAccess = false
reportGeneralTypeIssues = false
reportOptionalIterable = false

[tool.ruff]
line-length = 90
target-version = "py310"
select = ["ALL"]
ignore = ["S101", "ANN101"]

[tool.ruff.per-file-ignores]
"src/*.py" = ["N999"]
